project_id = "hulnpsulovzyqcmroxir"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
additional_redirect_urls = [
  "https://9df9fce3-3938-41fe-9b5b-d6d3b7ef4c4f.lovableproject.com/",
  "http://localhost:3000/",
  "http://localhost:8080/",
  "https://localhost:3000/",
  "https://localhost:8080/"
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.cloud-data]
verify_jwt = true
